### ISSUE TITLE
How to build the native code? 

### ISSUE THREAD

**Issue by jabrena** [Spartronics4915/SpartronicsLib#3]
Hi,

How to build the native code for T265 camera?

Many thanks in advance

Juan  Antonio

**Comment by pietroglyph** [comment]
Building the native code isn't too hard if you're not cross compiling to the RoboRIO. If you are then things are a little trickier.

Here is a recording of me building for both my native arch (x86 64), and cross compiling for the RoboRIO:
[![asciicast](https://asciinema.org/a/bp1WS10zhgIJvHA3CmsFY2AbX.svg)](https://asciinema.org/a/bp1WS10zhgIJvHA3CmsFY2AbX)

If you just want the binaries then you can also download the one's I've built:

[Here's a build of the native code for x86_64.](https://drive.google.com/file/d/1s0PPfRt5IMI8Q0T-iTyHoNIm7bYo8tgS/view?usp=sharing)

[Here's a build of the native code for the RoboRIO.](https://drive.google.com/open?id=1UiJSEcKcba1OHCMwYdMb2dy3GJvxHvpq)

[Here's a build of librealsense for the RoboRIO.](https://drive.google.com/file/d/1rBGq7EmbU_ZF0SkusAwgJds3DUUyltwi/view?usp=sharing)

Note that you will have to place libspartronicsnative.so into your home directory, because we only search within that path (this is a kludge that I will probably fix sometime within the next two weeks).

**Comment by jabrena** [comment]
I am thinking to build it for ARM5 (Lego mindstorms EV3) to add support for that hardware.

It could be interesting to add T265 support.

I like your approach and objects used with raw sensor data.

What do you think?

Cheers

**Comment by pietroglyph** [comment]
In that case you find that the trickiest part is cross compiling librealsense.

If the ev3 has a C++11 compiler and Linux then it should be possible. See [here](https://github.com/IntelRealSense/librealsense/compare/master...Spartronics4915:spartronics) to view the changes I made to cross compile librealsense and reduce its memory usage.

You will need to point many of those files to your cross-compilation toolchain.
